name: cap_shop
description: A stylish cap shop app built with Flutter.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies here

flutter:
  assets:
    - assets/images/
    - assets/icons/cart.png
    - assets/icons/remove.png
    - assets/icons/home.png
